version: '3.8'

services:
  # 前端服务
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend

  # 后端服务
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://secondbrain:secondbrain123@postgres:5432/secondbrain
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - minio
      - qdrant
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000

  # PostgreSQL 数据库
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=secondbrain
      - POSTGRES_USER=secondbrain
      - POSTGRES_PASSWORD=secondbrain123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis 缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO 对象存储
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  # Qdrant 向量数据库
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  redis_data:
  minio_data:
  qdrant_data: