"""add_message_branch_fields

Revision ID: 3e579dc16df9
Revises: ca26db314b38
Create Date: 2025-07-12 22:51:53.763647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e579dc16df9'
down_revision: Union[str, None] = 'ca26db314b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('is_private', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('annotations', sa.Column('tags', sa.JSON(), nullable=True))
    op.create_index('idx_annotation_document_user', 'annotations', ['document_id', 'user_id'], unique=False)
    op.create_index('idx_annotation_page', 'annotations', ['document_id', 'page_number'], unique=False)
    op.create_index('idx_annotation_type', 'annotations', ['type'], unique=False)
    op.add_column('messages', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('branch_name', sa.String(length=100), nullable=True, server_default='main'))
    op.add_column('messages', sa.Column('is_active_branch', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index('idx_message_branch', 'messages', ['branch_name'], unique=False)
    op.create_index('idx_message_parent', 'messages', ['parent_message_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'])
    op.add_column('notes', sa.Column('note_type', sa.String(length=20), nullable=False, server_default='manual'))
    op.add_column('notes', sa.Column('source_type', sa.String(length=20), nullable=True))
    op.add_column('notes', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('notes', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('notes', sa.Column('ai_prompt', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('generation_params', sa.JSON(), nullable=True))
    op.add_column('notes', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('notes', sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('idx_note_created', 'notes', ['created_at'], unique=False)
    op.create_index('idx_note_space_user', 'notes', ['space_id', 'user_id'], unique=False)
    op.create_index('idx_note_type', 'notes', ['note_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_note_type', table_name='notes')
    op.drop_index('idx_note_space_user', table_name='notes')
    op.drop_index('idx_note_created', table_name='notes')
    op.drop_column('notes', 'is_draft')
    op.drop_column('notes', 'version')
    op.drop_column('notes', 'generation_params')
    op.drop_column('notes', 'ai_prompt')
    op.drop_column('notes', 'ai_model')
    op.drop_column('notes', 'source_id')
    op.drop_column('notes', 'source_type')
    op.drop_column('notes', 'note_type')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('idx_message_parent', table_name='messages')
    op.drop_index('idx_message_branch', table_name='messages')
    op.drop_column('messages', 'is_active_branch')
    op.drop_column('messages', 'branch_name')
    op.drop_column('messages', 'parent_message_id')
    op.drop_index('idx_annotation_type', table_name='annotations')
    op.drop_index('idx_annotation_page', table_name='annotations')
    op.drop_index('idx_annotation_document_user', table_name='annotations')
    op.drop_column('annotations', 'tags')
    op.drop_column('annotations', 'is_private')
    # ### end Alembic commands ###